# Generated by Django 4.1 on 2022-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmx_patterns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
