# Generated by Django 4.1 on 2023-04-05 11:34
import random

from django.db import migrations
from faker import Faker


def forwards(apps, _):
    Monster = apps.get_model("htmx_patterns", "Monster")
    faker = Faker()
    created = []
    for i in range(0, 5):
        created.append(
            Monster.objects.create(
                name=faker.first_name(), is_happy=bool(random.randint(0, 1))
            )
        )
    return created


class Migration(migrations.Migration):

    dependencies = [
        ("htmx_patterns", "0002_alter_monster_name"),
    ]

    operations = [migrations.RunPython(forwards, lambda *args: None)]
