# Generated by Django 4.1 on 2023-04-13 18:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmx_patterns", "0003_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="monster",
            name="type",
            field=models.CharField(
                choices=[("humanoid", "Humanoid"), ("blob", "Blob"), ("leggy", "Leggy")],
                default="humanoid",
                max_length=50,
            ),
        ),
    ]
